directories:
  output: release
  buildResources: build
appId: com.digitalizador.doc
productName: Digitalizador de Documentos
asar: true
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target: nsis
  icon: electron/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 40.0.0
